android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId '6da76212-18bd-4ca9-becc-72ae67028403'
            beaconUrl 'https://bf04217tce.bf-dev.dynatracelabs.com/mbeacon'
          }
          userOptIn true
          agentBehavior.startupLoadBalancing true
          debug.agentLogging true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>6da76212-18bd-4ca9-becc-72ae67028403</string>
    <key>DTXBeaconURL</key>
    <string>https://bf04217tce.bf-dev.dynatracelabs.com/mbeacon</string>
    <key>DTXUserOptIn</key>
    <true/>
    <key>DTXStartupLoadBalancing</key>
    <true/>"
