name: dynatrace_flutter_plugin_example
description: Demonstrates how to use the dynatrace_flutter_plugin.

publish_to: 'none' 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynatrace_flutter_plugin: 
    path: ../
    # When depending on this package from a real application you should use:
    #   dynatrace_flutter_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    #path: ../

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
