name: dynatrace_flutter_plugin
description: The Dynatrace Flutter plugin helps auto-instrument your Flutter app with Dynatrace OneAgent for Android and iOS. It also provides an API to add manual instrumentation.
version: 2.237.0
homepage: "https://www.dynatrace.com/"

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter: 
    sdk: flutter
  path: ^1.8.0
  yaml: ^3.1.0
  xml: ^5.3.0

dev_dependencies:
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dynatrace.android.agent
        pluginClass: DynatraceFlutterPlugin
      ios:
        pluginClass: DynatraceFlutterPlugin